sudo: false
language: java
install: ./gradlew assemble
script: 
   - ./gradlew clean build
   - ./gradlew check
   - ./gradlew codeCoverageReport
after_success:
  - bash <(curl -s https://codecov.io/bash)
